name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@v3.22
        with:
        
          # Options
          user: DancingSnow
          template: classic
          base: header, activity, community, metadata
          config_timezone: Asia/Shanghai
          plugin_lines: yes
          plugin_people: yes
          plugin_people_types: followers, following
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_traffic: yes
          plugin_fortune: yes
          plugin_languages: yes
          plugin_stars: yes
          plugin_licenses: yes
          plugin_activity: yes

